version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest  # Use Node.js if you need it for any reason; replace if unnecessary
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            if [ -f package.json ]; then
              npm install
            else
              echo "No package.json found, skipping npm install."
            fi

  test:
    docker:
      - image: circleci/node:latest  # Use a testing image that suits your needs
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            if [ -f package.json ]; then
              npm test
            else
              echo "No package.json found, skipping tests."
            fi

  deploy:
    docker:
      - image: circleci/node:latest  # Use a deployment image that suits your needs
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            echo "Deploying the site..."
            # Add your deployment steps here, like uploading to a web server or pushing to a CDN

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
